sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libzmq-dev
language: php

php:
  - 5.6

before_script:
  - ./.travis.scripts/compile.sh

notifications:
  email:
    gwprod@gmail.com

script:
  - MYPHP=`make findphp`
  - export PATH=`dirname $MYPHP`:$PATH
  - $MYPHP -c /tmp/temp-php-config.ini -v
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$MYPHP $MYPHP -c /tmp/temp-php-config.ini -dxdebug.auto_trace=0 run-tests.php -q -x --show-diff